services:
  - type: web
    name: rainfall-prediction-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python train_model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
